import { useEffect, useState } from "react";
import { Pulse, CheckCircle, FolderOpen, GithubLogo, ShieldCheck, WarningCircle } from "@phosphor-icons/react";
type Health = { status: string; version: string; apiVersion: string; errorCode?: string; error?: string; metrics: { frames: number; dropped: number; maskFps: number; inferenceMs: number | null; device: string } };
declare global { interface Window { rvm?: { health(): Promise<Health>; openSource(): Promise<void>; openData(): Promise<void> } } }
const preview: Health = { status: "ready", version: "preview", apiVersion: "1.0", metrics: { frames: 1200, dropped: 0, maskFps: 24, inferenceMs: 31.2, device: "fixture" } };
export default function App() {
  const [health, setHealth] = useState<Health>(preview);
  useEffect(() => { if (!window.rvm) return; const refresh = () => window.rvm!.health().then(setHealth).catch(error => setHealth({ status: "unavailable", version: "—", apiVersion: "1.0", error: error.message, metrics: { frames: 0, dropped: 0, maskFps: 0, inferenceMs: null, device: "—" } })); refresh(); const timer = setInterval(refresh, 2000); return () => clearInterval(timer); }, []);
  const ready = health.status === "ready";
  return <main><header><div><ShieldCheck/><span><strong>Navbea RVM</strong><small>GPL-3.0 LOCAL MATTING SERVICE</small></span></div><nav><button onClick={() => void window.rvm?.openSource()}><GithubLogo/>Upstream source</button><button onClick={() => void window.rvm?.openData()}><FolderOpen/>Service data</button></nav></header><section className="hero"><span className={ready ? "ready" : "failed"}>{ready ? <CheckCircle/> : <WarningCircle/>}{health.status.toUpperCase()}</span><h1>Sequence-aligned alpha masks</h1><p>RVM reads a short-lived Camera Service stream and publishes local GRAY8 masks. It has no camera ownership or cloud credentials.</p></section><section className="grid"><Metric icon={<Pulse/>} label="Mask throughput" value={`${health.metrics.maskFps} FPS`}/><Metric icon={<Pulse/>} label="Inference" value={health.metrics.inferenceMs === null ? "—" : `${health.metrics.inferenceMs.toFixed(1)} ms`}/><Metric icon={<Pulse/>} label="Processed" value={String(health.metrics.frames)}/><Metric icon={<Pulse/>} label="Dropped" value={String(health.metrics.dropped)}/></section>{!ready && <section className="error"><WarningCircle/><div><strong>{health.errorCode || "RVM_UNAVAILABLE"}</strong><p>{health.error || "Install the signed model/runtime package and restart the service."}</p></div></section>}<footer>Service {health.version} · API {health.apiVersion} · {health.metrics.device}</footer></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article>{icon}<span><small>{label}</small><strong>{value}</strong></span></article>; }
