import {useEffect,useState} from 'react';
import {ArrowDown,CheckCircle,CircleNotch,FolderOpen,Info,ShieldCheck,WarningCircle} from '@phosphor-icons/react';
import ForegroundPreview from './ForegroundPreview';
import type {PreviewBridge} from './ForegroundPreview';
import StillModelsSection from './StillModelsSection';
import type {StillBridge} from './StillModelsSection';
import DeviceSection from './DeviceSection';
import type {DeviceBridge} from './DeviceSection';
import BenchmarkSection from './BenchmarkSection';
import type {BenchmarkBridge} from './BenchmarkSection';
type Health={status:string;version:string;errorCode?:string;error?:string;metrics:{threadMode?:string;maskFps:number;inferenceMs:number|null;device:string;lastStill?:{totalMs:number};providerFallback?:string|null}};
type Model={maxNativePixels?:number;id:string;name:string;architecture:string;precision:string;bytes:number;bundled?:boolean;downloaded:boolean;active:boolean;recommended:boolean;memoryRecommended:boolean;recommendedMemoryGiB:number;note:string};
type Models={available:boolean;error?:string;defaultModel:string;active:{id:string};models:Model[];switching:boolean;activeSessions:number;actualProvider?:string;hardware:{memoryGiB:number;freeMemoryGiB:number;logicalCores:number;platform:string;arch:string};download?:{id:string;phase:string;received:number;total:number;error?:string};lastError?:string|null;lastProbe?:{modelId:string;provider:string;precision:string;probeMs:number;nativeProvider?:string}};
type Bridge=PreviewBridge&StillBridge&DeviceBridge&BenchmarkBridge&{health():Promise<Health>;models():Promise<Models>;modelAction(action:'download'|'activate'|'cancel',id?:string):Promise<Models>;openSource():Promise<void>;openUpstream():Promise<void>;openLicense():Promise<void>;openNotices():Promise<void>;openSourceOffer():Promise<void>;openData():Promise<void>};
declare global{interface Window{rvm?:Bridge}}
export default function ModelsPage(){
 const [previewActive,setPreviewActive]=useState(false);
 const bridge=window.rvm;const [health,setHealth]=useState<Health|null>(null),[models,setModels]=useState<Models|null>(null),[error,setError]=useState(''),[connectionError,setConnectionError]=useState(''),[pending,setPending]=useState('');
 useEffect(()=>{if(!bridge)return;let closed=false,reading=false;const read=async()=>{if(reading)return;reading=true;try{const [h,m]=await Promise.all([bridge.health(),bridge.models()]);if(!closed){setHealth(h);setModels(m);setConnectionError('');}}catch(error){if(!closed){setConnectionError(message(error));setHealth(null);setModels(null);}}finally{reading=false;}};void read();const timer=setInterval(()=>void read(),1000);return()=>{closed=true;clearInterval(timer);};},[bridge]);
 const run=async(action:'download'|'activate'|'cancel',id?:string)=>{if(!bridge||pending)return;setPending(action+':'+id);setError('');try{setModels(await bridge.modelAction(action,id));}catch(error){setError(message(error));}finally{setPending('');}};
 const downloading=models?.download&&['downloading','verifying'].includes(models.download.phase);
 const active=models?.models?.find(item=>item.id===models.active.id);
 return <div className="rvm-shell"><header><div className="rvm-brand"><ShieldCheck/><span>Navbea RVM</span></div><button onClick={()=>void bridge?.openData()} disabled={!bridge}><FolderOpen/>Servis kayıtları</button></header><main>
  <div className="page-heading"><div><p className="eyebrow">YEREL GÖRÜNTÜ İŞLEME</p><h1>Görüntü motoru</h1><p>Mevcut modelini görüntüle. Diğer seçenekleri ihtiyacına göre indir ve doğrula.</p></div><span className="status" role="status">{models?.switching||pending?<CircleNotch className="spin"/>:health?.status==='ready'?<CheckCircle/>:<Info/>}{models?.switching?'Model doğrulanıyor':health?.metrics.threadMode==='calibrating'?'Donanım ölçülüyor':health?.status==='ready'?'Hizmet hazır':bridge?'Hizmet bekleniyor':'Masaüstü uygulaması gerekli'}</span></div>
  {(error||connectionError||models?.lastError||health?.error)&&<div className="notice" role="alert"><WarningCircle/><span>{error||connectionError||models?.lastError||health?.error}</span></div>}
  <section className="current-model"><div><span className="eyebrow">ETKİN MODEL</span><h2>{active?.name||'Mevcut model'}</h2><p>{active?.id===models?.defaultModel?'Paketle gelen MobileNetV3 FP32 · varsayılan profil':'Doğrulanmış isteğe bağlı model'}</p></div><div className="current-metrics"><span><small>Maske</small><strong>{health?.metrics.maskFps??'—'} FPS</strong></span><span><small>İşleme</small><strong>{health?.metrics.inferenceMs!=null?Math.round(health.metrics.inferenceMs)+' ms':'—'}</strong></span><span><small>Çalışma ortamı</small><strong>{health?.metrics.device?.replace('ExecutionProvider','')||'—'}</strong></span></div></section>
  <DeviceSection bridge={bridge} disabled={!!pending||previewActive||!!models?.switching}/>
  <BenchmarkSection bridge={bridge} disabled={!!pending||previewActive||!!models?.switching}/>
  <ForegroundPreview bridge={bridge} disabled={!!pending||!!models?.switching} onActiveChange={setPreviewActive}/>
  <section className="model-section"><div className="section-heading"><h2>Model seçenekleri</h2><p>İndirme etkin modeli değiştirmez. Geçiş yalnızca çekim oturumu ve canlı önizleme kapalıyken, çalışma testi geçince yapılır.</p></div>
   {!!models?.activeSessions&&<p className="notice"><Info/>Aktif çekim oturumu var. Model geçişi için oturumun bitmesini bekle.</p>}
   <div className="model-grid">{models?.models?.map(item=>{const job=models.download?.id===item.id?models.download:null;const progress=job?Math.min(100,Math.round(job.received/job.total*100)):0;return <article key={item.id} className={`model-card ${item.active?'active':''}`}><div className="model-title"><h3>{item.name}</h3>{item.active?<span>Etkin</span>:item.recommended?<span>Varsayılan</span>:<span>{item.precision.toUpperCase()}</span>}</div><p>{item.note}</p><div className="model-facts"><span>{Math.round(item.bytes/1048576)} MB</span><span>{item.architecture==='resnet50'?'Daha ağır ağ':'Dengeli ağ'}</span>{item.maxNativePixels&&<span>En fazla {Math.round(item.maxNativePixels/1000000)} MP</span>}</div>{!item.memoryRecommended&&<p className="model-warning">Bu model için en az {item.recommendedMemoryGiB} GB RAM önerilir. Mevcut model daha uygun olabilir.</p>}
    {job&&['downloading','verifying'].includes(job.phase)&&<div className="download-progress" role="status"><progress max={100} value={progress}/><span>{job.phase==='verifying'?'Dosya doğrulanıyor…':`İndiriliyor · %${progress}`}</span></div>}{job?.error&&<p className="model-warning">{job.error}</p>}
    <div className="model-actions">{item.active?<button disabled><CheckCircle/>Kullanılıyor</button>:item.downloaded?<button className="primary" disabled={!!pending||previewActive||models.switching||models.activeSessions>0} onClick={()=>void run('activate',item.id)}>Doğrula ve kullan</button>:<button disabled={!!pending||!!downloading} onClick={()=>void run('download',item.id)}><ArrowDown/>İndir</button>}{job&&['downloading','verifying'].includes(job.phase)&&<button disabled={!!pending} onClick={()=>void run('cancel')}>İptal et</button>}</div></article>;})}</div>
   {!models?.available&&<div className="notice"><Info/>{models?.error||'Model listesi RVM masaüstü uygulamasında, hizmet bağlantısı kurulduğunda görünür.'}</div>}
  </section>
  <StillModelsSection bridge={bridge} disabled={!!pending||previewActive||!!models?.switching}/>
  {models?.lastProbe&&<section className="probe-result"><CheckCircle/><p><strong>Son çalışma testi geçti.</strong> {models.lastProbe.modelId} · {models.lastProbe.provider.replace('ExecutionProvider','')} · küçük canlı/native örnek testi {models.lastProbe.probeMs} ms. Bu değer kameranın gerçek çekim süresi değildir.</p></section>}
  <details className="advanced"><summary>Kaynaklar ve lisanslar</summary><p>RVM modelleri GPL-3.0 koşullarıyla, resmî v1.0.0 sürümünden indirilir. BiRefNet fotoğraf modelleri MIT lisanslıdır ve sabitlenmiş Hugging Face sürümünden indirilir. Her dosya sabit SHA-256 ve boyutla doğrulanır.</p><div className="links"><button disabled={!bridge} onClick={()=>void bridge?.openSource()}>Karşılık gelen kaynak</button><button disabled={!bridge} onClick={()=>void bridge?.openLicense()}>GPL lisansı</button><button disabled={!bridge} onClick={()=>void bridge?.openNotices()}>Üçüncü taraf bildirimleri</button><button disabled={!bridge} onClick={()=>void bridge?.openSourceOffer()}>Kaynak teklifi</button><button disabled={!bridge} onClick={()=>void bridge?.openUpstream()}>Resmî model projesi</button></div></details>
  <footer>RVM {health?.version||'—'} · Model değişimi kamera seçimini değiştirmez.</footer>
 </main></div>;
}
function message(error:unknown){const raw=error instanceof Error?error.message:String(error);if(/ENOENT|ECONNREFUSED/.test(raw))return 'RVM hizmetine bağlanılamıyor. Başlat menüsündeki ZoomSelfie - Start services and Kiosk kısayolunu açın.';return raw.replace(/^(?:Error: )?Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,'');}
