import {useEffect,useState} from 'react';
import {ArrowDown,CheckCircle,CircleNotch,Info,WarningCircle} from '@phosphor-icons/react';
type StillModel={id:string;name:string;architecture:string;precision?:string;bytes:number;builtin?:boolean;downloaded:boolean;active:boolean;recommended:boolean;memoryRecommended:boolean;recommendedMemoryGiB:number;note:string};
type StillMatte={model:string;used:string;provider?:string|null;fallback?:string;error?:string;inferenceMs?:number;totalMs?:number;deadlineMs:number;at?:string};
export type StillModels={available:boolean;error?:string;defaultModel:string;active:{id:string};models:StillModel[];switching:boolean;activeSessions:number;deadlineMs:number;download?:{id:string;phase:string;received:number;total:number;error?:string};lastError?:string|null;lastProbe?:{modelId:string;provider:string;probeMs:number;totalMs:number;warmupMs:number}|null;runtime?:{id:string;status:'loading'|'ready'|'unavailable';provider?:string;warmupMs?:number;reason?:string}|null;lastStillMatte?:StillMatte|null};
export type StillBridge={stillModels():Promise<StillModels>;stillModelAction(action:'download'|'activate'|'cancel',id?:string):Promise<StillModels>};
const fallbackText:Record<string,string>={timeout:'süre sınırı aşıldı',busy:'önceki fotoğraf hâlâ işleniyordu',loading:'model henüz yükleniyordu',unavailable:'model kullanılamıyor',error:'model hata verdi'};
const provider=(value?:string|null)=>value?.replace('ExecutionProvider','')||'—';
export default function StillModelsSection({bridge,disabled}:{bridge?:StillBridge;disabled:boolean}){
 const [models,setModels]=useState<StillModels|null>(null),[error,setError]=useState(''),[pending,setPending]=useState('');
 useEffect(()=>{if(!bridge?.stillModels)return;let closed=false,reading=false;const read=async()=>{if(reading)return;reading=true;try{const value=await bridge.stillModels();if(!closed)setModels(value);}catch{if(!closed)setModels(null);}finally{reading=false;}};void read();const timer=setInterval(()=>void read(),1000);return()=>{closed=true;clearInterval(timer);};},[bridge]);
 const run=async(action:'download'|'activate'|'cancel',id?:string)=>{if(!bridge||pending)return;setPending(action+':'+id);setError('');try{setModels(await bridge.stillModelAction(action,id));}catch(error){setError(message(error));}finally{setPending('');}};
 const downloading=models?.download&&['downloading','verifying'].includes(models.download.phase);
 const seconds=((models?.deadlineMs??5000)/1000).toFixed(0);
 const runtime=models?.runtime,last=models?.lastStillMatte;
 return <section className="model-section"><div className="section-heading"><h2>Fotoğraf maskesi</h2><p>Canlı önizleme her zaman RVM ile çalışır. Çekilen fotoğraf seçilen modelle yeniden maskelenir; model {seconds} sn içinde bitmezse otomatik olarak RVM sonucu kullanılır.</p></div>
  {(error||models?.lastError)&&<div className="notice" role="alert"><WarningCircle/><span>{error||models?.lastError}</span></div>}
  {runtime&&<p className={runtime.status==='unavailable'?'notice':'hardware-line'} role="status">{runtime.status==='loading'?<><CircleNotch className="spin"/> Model GPU'ya yükleniyor…</>:runtime.status==='ready'?<><CheckCircle/> Hazır · {provider(runtime.provider)} · ısınma {runtime.warmupMs} ms</>:<><WarningCircle/> Model kullanılamıyor; fotoğraflar RVM ile maskeleniyor. {runtime.reason}</>}</p>}
  {last&&<p className="hardware-line">Son çekim: {last.used==='rvm'?`RVM kullanıldı (${fallbackText[last.fallback||'']||last.fallback||'—'})`:`${last.model} · ${provider(last.provider)} · maske ${last.inferenceMs} ms · toplam ${last.totalMs} ms`}</p>}
  <div className="model-grid">{models?.models?.map(item=>{const job=models.download?.id===item.id?models.download:null;const progress=job?Math.min(100,Math.round(job.received/job.total*100)):0;const busy=!!pending||disabled||models.switching||models.activeSessions>0;return <article key={item.id} className={`model-card ${item.active?'active':''}`}><div className="model-title"><h3>{item.name}</h3>{item.active?<span>Etkin</span>:item.recommended?<span>Varsayılan</span>:<span>{(item.precision||'').toUpperCase()}</span>}</div><p>{item.note}</p><div className="model-facts">{item.builtin?<span>İndirme yok</span>:<span>{Math.round(item.bytes/1048576)} MB</span>}<span>{item.builtin?'CPU':'GPU gerekir'}</span></div>{!item.builtin&&!item.memoryRecommended&&<p className="model-warning">Bu model için en az {item.recommendedMemoryGiB} GB RAM önerilir.</p>}
   {job&&['downloading','verifying'].includes(job.phase)&&<div className="download-progress" role="status"><progress max={100} value={progress}/><span>{job.phase==='verifying'?'Dosya doğrulanıyor…':`İndiriliyor · %${progress}`}</span></div>}{job?.error&&<p className="model-warning">{job.error}</p>}
   <div className="model-actions">{item.active?<button disabled><CheckCircle/>Kullanılıyor</button>:item.downloaded?<button className="primary" disabled={busy} onClick={()=>void run('activate',item.id)}>{pending==='activate:'+item.id?<><CircleNotch className="spin"/>Süre testi yapılıyor…</>:item.builtin?'RVM kullan':'Süre testi yap ve kullan'}</button>:<button disabled={!!pending||!!downloading} onClick={()=>void run('download',item.id)}><ArrowDown/>İndir</button>}{job&&['downloading','verifying'].includes(job.phase)&&<button disabled={!!pending} onClick={()=>void run('cancel')}>İptal et</button>}</div></article>;})}</div>
  {!models?.available&&<div className="notice"><Info/>{models?.error||'Fotoğraf maskesi seçenekleri hizmet bağlantısı kurulduğunda görünür.'}</div>}
  {models?.lastProbe&&<section className="probe-result"><CheckCircle/><p><strong>Son süre testi geçti.</strong> {models.lastProbe.modelId} · {provider(models.lastProbe.provider)} · 24 MP fotoğraf: maske {models.lastProbe.probeMs} ms, kenar rengi ve kodlama dahil {models.lastProbe.totalMs} ms (sınır {seconds} sn).</p></section>}
 </section>;
}
function message(error:unknown){const raw=error instanceof Error?error.message:String(error);return raw.replace(/^(?:Error: )?Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,'');}
